#!/usr/bin/env ruby

require 'bundler/setup'
require 'comtec-dr'

ARGV.each do |arg|
  path = Pathname arg
  if path.file? && path.basename.to_s.end_with?('.MOV')
    CSV.open("#{path.basename.to_s.gsub('.MOV','')}.csv",'w') do |csv|
      track = ComtecDR::GpsTrack.analyze path.to_s
      track.track.each{|t| csv << t.csv_line}
    end
  elsif path.directory?
    CSV.open("#{path.basename.to_s}.csv",'w') do |csv|
      path.children(with_directory: false).each do |child_path|
        if child_path.file? && child_path.basename.to_s.end_with?('.MOV')
          track = ComtecDR::GpsTrack.analyze child_path.to_s
          track.track.each{|t| csv << t.csv_line}
        end
      end
    end
  end
end
